version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: credicard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  web:
    build: /app
    container_name: fastapi_app
    volumes:
      - /app/data
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  config-db:
    container_name: fastapi_app
    command: [ "poetry", "run", "alembic", "upgrade", "head" ]
    depends_on:
      - web