version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: credicard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  web:
    build: ./creditcard
    container_name: fastapi_app
    command: ["poetry", "run", "uvicorn", "src.adapters.inbound.rest.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./creditcard
    ports:
      - "8000:8000"
    depends_on:
      - postgres
